name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - name: Install linters
        run: pip install black flake8 mypy || true

      - name: Run linters
        run: |
          black --check . || true
          flake8 || true
          mypy . || true

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      DATABASE_URL: sqlite+aiosqlite:///./test.db
      # кладём и корень, и src в sys.path — покрываем оба варианта импорта
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # не обязательно, но если есть packaging — норм
          if [ -f setup.py ] || [ -f pyproject.toml ]; then pip install -e .; fi
          pip install "httpx>=0.28" pytest pytest-asyncio aiosqlite

      - name: Run tests
        env:
          PYTEST_ADDOPTS: "-p pytest_asyncio --asyncio-mode=auto -q"
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            set -e
            echo "🚀 Connecting to server and deploying AIMektep..."

            # Создаём папку проекта, если её нет
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/AIMektep" ]; then
              echo "📁 Cloning repo for the first time..."
              git clone https://${{ secrets.TOKEN_DEPLOY }}@github.com/irinaqqq/AIMektep.git /home/${{ secrets.SERVER_USER }}/AIMektep
            fi

            cd /home/${{ secrets.SERVER_USER }}/AIMektep

            echo "🧭 Pulling latest changes..."
            git pull origin main

            echo "🔧 Building and restarting container..."
            docker compose down
            docker compose up -d --build

            echo "✅ Deployment completed successfully!"
